// This file was generated by a python script.
// Do not edit this file... YOUR CHANGES WILL GET OVERWRITTEN...
// Edit proj/xdl_types.json instead.

#include "util/datatype1.hh"

 /*
   The list of XDL types specific to this application.
 */
using namespace std;

const char* DataTypeNames[] = {
    "u8",
    "u16",
    "u24",
    "u32",
    "u64",
    "u128",
    "u256",
    "i8",
    "i16",
    "i24",
    "i32",
    "i64",
    "i128",
    "i256",
    "f32",
    "f64",
    "bool",
    "date",
    "juldate",
    "timestamp",
    "string8",
    "string16",
    "string32",
    "string64",
    "utf8_8",
    "utf8_16",
    "utf8_32",
    "utf8_64",
    "utf16_8",
    "utf16_16",
    "utf16_32",
    "utf16_64",
    "regex",
    "list8",
    "list16",
    "list32",
    "list64",
    "struct8",
    "struct16",
    "struct32",
    "dynamiclist8",
    "dynamiclist16",
    "func8",
    "func16",
    "funcparam8",
    "funcparam16",
    "loop1",
    "loop2",
    "loop4",
    "bitvec8",
    "bitvec16",
    "bitvec32",
    "bitvec64",
    "bitvec32_int",
    "bitvec64_int",
    "bitfields",
    "arithmetic",
    "jpeg",
    "jpeglist",
    "blob16",
    "blob32",
    "blob64",
    "bigint",
    "enum_size does not really exist",
};


unordered_map<string,DataType> mapnames;
void loadmap(){
  for (int i = 0; i < int(DataType::ENUM_SIZE); i++)
    mapnames[DataTypeNames[i]] = (DataType)i;
}