// This file was generated by a python script.
// Do not edit this file... YOUR CHANGES WILL GET OVERWRITTEN...
// Edit proj/xdl_types.json instead.
#pragma once

#include <cstdint>
#include <iostream>
#include <unordered_map>
#include <vector>

/*
   The list of XDL types specific to this application.
 */
enum class DataType {
  U8,
  U16,
  U24,
  U32,
  U64,
  U128,
  U256,
  I8,
  I16,
  I24,
  I32,
  I64,
  I128,
  I256,
  F32,
  F64,
  BOOL,
  DATE,
  JULDATE,
  TIMESTAMP,
  STRING8,
  STRING16,
  STRING32,
  STRING64,
  UTF8_8,
  UTF8_16,
  UTF8_32,
  UTF8_64,
  UTF16_8,
  UTF16_16,
  UTF16_32,
  UTF16_64,
  REGEX,
  LIST8,
  LIST16,
  LIST32,
  LIST64,
  STRUCT8,
  STRUCT16,
  STRUCT32,
  DYNAMICLIST8,
  DYNAMICLIST16,
  FUNC8,
  FUNC16,
  FUNCPARAM8,
  FUNCPARAM16,
  LOOP1,
  LOOP2,
  LOOP4,
  BITVEC8,
  BITVEC16,
  BITVEC32,
  BITVEC64,
  BV32,
  BV64,
  BITFIELDS,
  ARITHMETIC,
  JPEG,
  JPEGLIST,
  BLOB16,
  BLOB32,
  BLOB64,
  BIGINT,
  ENUM_SIZE,
};


extern const char* DataTypeNames[];
extern std::unordered_map<std::string, DataType> mapnames;
extern void loadmap();