#!/usr/bin/env python3

# It's expected that this file will be run from within the proj directory, if
# you run it from elsewhere things may break.
# (Why on earth are you running this tho?)

import json
from pathlib import Path


def main():
    with open("errors.json", "r") as f:
        error_dict = json.load(f)

    names_file_path = Path(__file__).parents[1] / "src/opengl/ErrNames.cc"
    codes_file_path = Path(__file__).parents[1] / "src/opengl/Errcode.hh"

    with open(names_file_path, "w") as names, open(codes_file_path, "w") as codes:
        codes.write(
            """\
// This file was generated by a python script.
// Do not edit this file... YOUR CHANGES WILL GET OVERWRITTEN...
// Edit proj/errors.json instead.
#pragma once

/*
   The list of errors specific to this application.
 */
enum class Errcode {\n"""
        )

        names.write(
            """\
// This file was generated by a python script.
// Do not edit this file... YOUR CHANGES WILL GET OVERWRITTEN...
// Edit proj/errors.json instead.
#include "util/Ex.hh"
/*
   The list of errors specific to this application.
   This file must be included BEFORE #include "Log.hh"
 */
const char* Ex::errNames[] = {\n"""
        )

        for name, code in error_dict.items():
            names.write(f'    "{code}",\n')
            codes.write(f"  {name},\n")

        codes.write("};")
        names.write("};")


if __name__ == "__main__":
    main()
