#pragma once

enum class Errcode {
	BAD_PROTOCOL,
	FILE_NOT_FOUND,
	PERMISSION_DENIED,
	DISK_FAILURE,
	OUT_OF_MEMORY,
	OUT_OF_DISK,
	CONNECTION_FAILURE,
	CERTIFICATE_EXPIRED,
	CERTIFICATE_INVALIDATED,
	PERMISSION_NOWRITE,
	PERMISSION_NOEXEC,
	PERMISSION_NOREAD,
	CLIENT_INVALID,
	SERVER_INVALID,
	REPOSITORY_TAMPERED,
	CLIENT_UPDATE,
	GETADDRINFO,
	SOCKET,
	SETSOCKOPT,
	SOCKET_BIND,
	NO_BIND,
	LISTEN,
	SIGACTION,
	ILLEGAL_SERVLETID,
	CANNOT_CLOSE
};
